name = "SparseSVM"
uuid = "24a8cbec-6934-40d2-ae7a-ff7fd552163d"
authors = ["Alfonso Landeros <alanderos@ucla.edu>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
